@startuml
skinparam componentStyle uml2
package "Local Server" as LocalServer {
  component "App Server"
  component Database
}

package MobileDevice {
  component "Installed Progressive Web App" {
    component Functionality {
      component "Patient Enrollment" {
        component "Patient Identification"
      }
      component "Health Record System"
      component "Patient Processing System for stages of care"
    }
    component Implementation {
      component "PWA UI" as UI
      note right of UI
                Likely a cached SPA with client routing.
                Any browser supporting service workers should also support this.
                Pages should be as simple as possible - largely static - 
                to not require significant CPU or memory resources on the device.
                Strict client side validation should be implemented.
                All data should be written to a local db such as RxDB and synced when possible.
      end note
      component "On Device DB"
      component "Syncing system with service workers and sockets/api/long polling"
    }
  }
  component "Mobile Dashboard" {

  }

}
package "Dashboard Display" {
  component "Full Screen Dashboard" {

  }
}

component "Dashboard" {
  component "Local Data"
  component "Syncing System"
  component "Data Display" {
    component "Patient number"
    component "Patient illnesses"
    component "In-patient treatment duration"
    component "Bed occupation rate"
    component "Last sync"
    component "Sync error message with suggested action"
  }
}

note left of LocalServer
  - Hosts server application and database
  - Connects to mobile devices via local WiFi
  - Supports real-time data sharing
  - Operates offline
  - Has synchronization capabilities
end note


@enduml
