@startuml

enum "Media Enum" as MediaEnum {
  IDENTIFYING
  MEDICAL
}
enum "Attribute Enum" as AttributeEnum {
  IDENTIFYING
  MEDICAL
  CONTACT 
}
enum "Value Enum" as ValueEnum {
  STRING
  INTEGER
  FLOAT
  etc.
}
enum "Treatment Enum" as TreatmentEnum {
  SET_BONE
  ANTIBIOTICS
  etc.
}
enum "Urgency Enum" as UrgencyEnum {
  VERY_HIGH
  HIGH
  MEDIUM
  LOW
}
enum "Triage Result Enum" as TriageResultEnum {
  ADMIT
  OUTPATIENT
  DISCHARGE
}
enum "Triage Type Enum" as TriageTypeEnum {
  INJURY
  FEVER
  etc.
}
enum "Action Enum" as ActionEnum {
  CONTINUE_TREATMENT
  DISCHARGE
  TRANSITION_TO_INPATIENT 
  TRANSITION_TO_OUTPATIENT
  ...This needs some more thought as if it's CONTINUE_TREATMENT the decision refers to a record
}
enum "Status Enum" as StatusEnum {
  NONE
  DISCHARGED
  INPATIENT
  OUTPATIENT
}
@enduml
